### ISSUE TITLE
Does iniconfig save or just ignore comments

### ISSUE THREAD

**Issue by DevPlayer-** [RonnyPfannschmidt/iniconfig#1]
The readme says it supports comments everywhere. But does that mean it supports recognizing comments but when you save the config those comments disappear? Or does iniconfig retain the location of the comments relative the thing they comments are commenting on?

**Comment by DevPlayer-** [comment]
Please provide example for updating and saving key values and the INI file.

**Comment by RonnyPfannschmidt** [comment]
there is no write support, iniconfig is a pure reader

writing a correct writer/updater that correctly keeps comments is actually a hard problem that at least i don't want to solve, if you think you can make a non-fragile solution feel free to propose
