### ISSUE TITLE
Building wheel for iniconfig failed: Permission denied

### ISSUE THREAD

**Issue by hugovk** [RonnyPfannschmidt/iniconfig#16]
The newest iniconfig 1.1.0, and 1.1.1 (with #14), fails on ppc64le / Python 3.7. Other (non-exhaustive) combos pass:

* https://travis-ci.org/github/python-pillow/Pillow/builds/735677531

```
Collecting pytest
  Using cached pytest-6.1.1-py3-none-any.whl (272 kB)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /home/travis/virtualenv/python3.7.2/lib/python3.7/site-packages (from pytest) (18.2.0)
Collecting iniconfig
  Downloading iniconfig-1.1.1.tar.gz (8.1 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting toml
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting pluggy<1.0,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting py>=1.8.2
  Using cached py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting packaging
  Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Using cached importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Requirement already satisfied, skipping upgrade: six in /home/travis/virtualenv/python3.7.2/lib/python3.7/site-packages (from packaging->pytest) (1.12.0)
Collecting zipp>=0.5
  Using cached zipp-3.3.0-py3-none-any.whl (5.3 kB)
Building wheels for collected packages: iniconfig
  WARNING: Building wheel for iniconfig failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/ca'
Failed to build iniconfig
ERROR: Could not build wheels for iniconfig which use PEP 517 and cannot be installed directly
```

---

An earlier build with 1.0.1 passed:

* https://travis-ci.org/github/python-pillow/Pillow/builds/735636960

**Comment by jhon9392** [comment]
also receiving same error for current and previous versions..
error -  
WARNING: Building wheel for iniconfig failed: [Errno 13] Permission denied: '/.cache
ERROR: Could not build wheels for iniconfig which use PEP 517 and cannot be installed directly
platform - linux - gitlab runner

**Comment by hugovk** [comment]
More testing narrows it down to ppc64le (at least on Python 3.6-3.9):

https://travis-ci.org/github/hugovk/Pillow/builds/735681024

(It installs fine for Python 3.7, fails for a likely unrelated reason, probably I forgot a dependency.)

**Comment by hugovk** [comment]
We have a workaround to run `sudo chown $USER ~/.cache/pip/wheels` on `ppc64le`, which we already had to do for `s390x`:

* https://github.com/python-pillow/Pillow/pull/4978

This was originally suggested at:

* https://travis-ci.community/t/permission-issue-while-building-wheels-for-various-python-packages/7822/12

Not sure if this is really an iniconfig issue but rather a Travis one, so I'll close this.

**Comment by RonnyPfannschmidt** [comment]
Probably should publish wheels to be sure

**Comment by hugovk** [comment]
Yes, that sounds like a good idea too 👍
